site_name: 许鹏的学习文档
nav:
    - 目录: index.md
    - 开发环境搭建:
        - 安装虚拟机版本Windows: 开发环境搭建/安装虚拟机版本Windows/安装虚拟机版本Windows.md
        - 安装虚拟机版本Ubuntu: 开发环境搭建/安装虚拟机版本Ubuntu/安装虚拟机版本Ubuntu.md
        - VSCode开发环境搭建:
            - 安装配置: 开发环境搭建/VSCode开发环境搭建/安装配置.md
            - 常用开发插件: 开发环境搭建/VSCode开发环境搭建/常用开发插件.md          
        - Node.js开发环境搭建: 开发环境搭建/Node.js开发环境搭建.md
        - Nginx环境搭建: 开发环境搭建/Nginx环境搭建.md
        - Vue.js开发环境搭建: 开发环境搭建/Vue.js开发环境搭建.md
    - 开发语言:
        - Go语言开发:
            - 开发环境搭建:
                - Ubuntu开发环境搭建: 开发语言/Go语言开发/开发环境搭建/Go语言Ubuntu开发环境搭建.md
                - Windows开发环境搭建: 开发语言/Go语言开发/开发环境搭建/Go语言Windows开发环境搭建.md
                - 模块管理: 开发语言/Go语言开发/开发环境搭建/模块管理.md
                - 可执行文件压缩: 开发语言/Go语言开发/开发环境搭建/可执行文件压缩.md
        - Java语言开发:
            - 开发环境搭建:
                - Linux下安装JDK: 开发语言/Java语言开发/开发环境搭建/Ubuntu20.04安装JDK(java环境).md
                - Linux下配置Maven环境: 开发语言/Java语言开发/开发环境搭建/Ubuntu20.04下配置Maven环境.md
                - 使用IDEA配置Maven:  开发语言/Java语言开发/开发环境搭建/使用IDEA配置Maven.md
                - SpringBoot第一个程序: 开发语言/Java语言开发/开发环境搭建/SpringBoot第一个程序.md
                - Dockerfile部署SpringBoot项目: 开发语言/Java语言开发/开发环境搭建/IDEA连接远程服务器Docker部署SpringBoot项目.md
    - 中间件:
        - Mysql:
            - 如何开启慢Sql日志: 中间件/Mysql/如何开启慢Sql日志.md
            - 如何设置数据表字符编码: 中间件/Mysql/如何设置数据表字符编码.md
            - Mysql中Null值是如何存放的: 中间件/Mysql/Mysql中Null值是如何存放的.md
    - 计算机操作系统:
        - 硬件结构: 
            - CPU是如何执行程序的: 计算机操作系统/硬件结构/CPU是如何执行程序的.md
    - 计算机网络:
        - HTTP/HTTPS:
            - 30张图解HTTP常见的面试题: 计算机网络/HTTP与HTTPS/30张图解HTTP常见的面试题.md
            - URI和URL区别和关联: 计算机网络/HTTP与HTTPS/URI和URL区别和关联.md
            - 有了HTTP协议为什么还要有websocket协议: 计算机网络/HTTP与HTTPS/有了HTTP协议为什么还要有websocket协议.md
            - HTTP的Keep-Alive与TCP的Keep-Alive的区别: 计算机网络/HTTP与HTTPS/HTTP的Keep-Alive与TCP的Keep-Alive的区别.md
    - 微服务与分布式:
        - 微服务和分布式的区别和联系: 微服务与分布式/微服务和分布式的区别和联系.md
        - HTTP和RPC的区别: 微服务与分布式/HTTP和RPC的区别.md
        - 一致性Hash算法: 微服务与分布式/一致性Hash算法.md
    - 设计模式(23种):
        - 创建型模式: 
            - 简单工厂模式: 设计模式/创建型模式/简单工厂模式.md
            - 工厂方法模式: 设计模式/创建型模式/工厂方法模式.md
            - 抽象工厂模式: 设计模式/创建型模式/抽象工厂模式.md
            - 建造者模式: 设计模式/创建型模式/建造者模式.md
            - 原型模式: 设计模式/创建型模式/原型模式.md
            - 单例模式: 设计模式/创建型模式/单例模式.md
        - 结构型模式:
            - 外观模式: 设计模式/结构型模式/外观模式.md
            - 适配器模式: 设计模式/结构型模式/适配器模式.md
            - 代理模式: 设计模式/结构型模式/代理模式.md
            - 组合模式: 设计模式/结构型模式/组合模式.md
            - 享元模式: 设计模式/结构型模式/享元模式.md
            - 装饰模式: 设计模式/结构型模式/装饰模式.md
            - 桥接模式: 设计模式/结构型模式/桥接模式.md
    - 领域驱动设计:
        - 参考系列文章: 领域驱动设计/参考系列文章.md
        - 开源架构: 领域驱动设计/开源架构.md
        - 程序目录结构: 领域驱动设计/程序目录结构.md
        - 内部博客系列:
            - 1.开篇: 领域驱动设计/内部博客系列/1.开篇.md
            - 2.聚合: 领域驱动设计/内部博客系列/2.聚合.md
            - 3.存储库: 领域驱动设计/内部博客系列/3.存储库.md
            - 4.领域服务: 领域驱动设计/内部博客系列/4.领域服务.md
            - 5.应用服务: 领域驱动设计/内部博客系列/5.应用服务.md
            - 6.六边形架构: 领域驱动设计/内部博客系列/6.六边形架构.md
    - Docker开发技术:
        - 环境搭建: Docker开发技术/Ubuntu20.04上安装和使用Docker.md
    - Kubernetes开发技术:
        - Kubernetes部署:
            - 部署Kubernetes: Kubernetes开发技术/Kubernetes部署/部署一套完整的Kubernetes高可用集群.md
            - 部署:Ingress-nginx: Kubernetes开发技术/Kubernetes部署/通过Ingress-nginx暴露service给外部网络访.md
            - 部署dashboard: Kubernetes开发技术/Kubernetes部署/k8s通过ingress部署dashboard.md
            - 部署NFS网络存储: Kubernetes开发技术/Kubernetes部署/Kubernetes集群部署NFS网络存储.md
            - 部署coredns: Kubernetes开发技术/Kubernetes部署/kubernetes二进制部署coredns.md
            - 部署Helm3: Kubernetes开发技术/Kubernetes部署/Helm3部署安装.md
            - 部署harbor: Kubernetes开发技术/Kubernetes部署/Kubernetes集群仓库使用Helm3部署harbor.md
            - 持久化存储: Kubernetes开发技术/Kubernetes部署/一文带你深入了解K8S持久化存储解决方案.md
            - 提供动态分配卷: Kubernetes开发技术/Kubernetes部署/Kubernetes中部署NFSProvisioner为NFS提供动态分配卷.md
            - tab指令: Kubernetes开发技术/Kubernetes部署/解决k8s命令tab不管用.md
            - pod通信: Kubernetes开发技术/Kubernetes部署/k8s集群外的主机访问pod的解决方案.md
        - KongAPI网关:
            - K8s方式安装部署: Kubernetes开发技术/KongAPI网关/K8s方式安装部署.md
            - Konga可视化工具部署: Kubernetes开发技术/KongAPI网关/Konga可视化工具部署.md
    - 持续集成(CI/CD):
        - Drone: 
            - Docker部署Drone: 持续集成/Drone/Docker部署drone.md
            - Drone使用私有镜像仓库: 持续集成/Drone/Drone使用harbor私有镜像仓库拉取镜像.md
            - Drone相关的环境变量: 持续集成/Drone/Drone相关的环境变量.md
        - Jenkins:
            - 自动化部署SpringBoot项目:  持续集成/Jenkins/Jenkins自动化部署SpringBoot项目.md         
    - 文档管理:
        - Seafile+Onlyoffice部署: 文档管理/seafile+onlyoffice部署.md
    - 代码私有仓库部署: 
        - 使用Docker部署Gitlab: Gitlab私有仓库搭建/使用Docker部署Gitlab.md
        - gitlab设置中文:  Gitlab私有仓库搭建/gitlab设置中文.md
        - Gitlab定时备份: Gitlab私有仓库搭建/Gitlab定时备份.md
        - Gitlab配置邮件服务: Gitlab私有仓库搭建/Gitlab配置邮件服务.md
    - 操作系统相关:     
        - Ubuntu相关知识:
            - Ubuntu修改DNS: 操作系统相关知识/Ubuntu/Ubuntu修改DNS.md  
            - 定制ubuntu_iso镜像: 操作系统相关知识/Ubuntu/使用Cubic定制ubuntu_iso镜像.md  
            - Ubuntu16.04导入根证书: 操作系统相关知识/Ubuntu/Ubuntu16.04导入根证书.md 
            - 64位Ubuntu兼容32位程序: 操作系统相关知识/Ubuntu/Ubuntu16.04(64位)兼容32位程序.md 
            - 桌面左侧任务栏到屏幕底部: 操作系统相关知识/Ubuntu/移动Ubuntu16.04桌面左侧任务栏到屏幕底部.md
        - Windows相关知识:
            - Windows系统下载网站: 操作系统相关知识/Windows/Windows系统下载网站(推荐).md
            - 使用NSIS制作安装包: 操作系统相关知识/Windows/使用NSIS制作安装包.md
        - 再生龙:
            - 再生龙备份还原操作系统: 操作系统相关知识/再生龙/再生龙备份还原操作系统.md
theme:
    name: 'material'
    favicon: assets/image/favicon.ico
    logo: assets/image/favicon.ico
    feature:
        tabs: false


markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
    - toc:
        permalink: true
    - footnotes
    - pymdownx.superfences
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.tasklist:
        custom_checkbox: true
