apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  capacity: 
    storage: 8Gi
  accessModes:   
    - ReadWriteOnce
  storageClassName: prometheus-data
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/server
    server: 172.31.10.252
